//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalMenu.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalMenuEntities1 : DbContext
    {
        public DigitalMenuEntities1()
            : base("name=DigitalMenuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblAdminProduct> tblAdminProducts { get; set; }
        public virtual DbSet<tblBook> tblBooks { get; set; }
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<tblChef> tblChefs { get; set; }
        public virtual DbSet<tblChefProduct> tblChefProducts { get; set; }
        public virtual DbSet<tblFood> tblFoods { get; set; }
        public virtual DbSet<tblFoodType> tblFoodTypes { get; set; }
        public virtual DbSet<tblSeller> tblSellers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
