//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalMenu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAdminProduct
    {
        [Key]
        public int AdPdId { get; set; }
        [Required]
        [Display(Name ="Select Seller")]
        public Nullable<int> SelId { get; set; }
        [Required]
        public string Products { get; set; }
        [Required]
        public string PstDate { get; set; }
        [Required]
        public string DeliverDate { get; set; }
        [Required]
        public string Replay { get; set; }
        [Required]
        public string RpDate { get; set; }
    
        public virtual tblSeller tblSeller { get; set; }
    }
}
