//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalMenu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int BkId { get; set; }
        public Nullable<int> FId { get; set; }
        public Nullable<int> UsrId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> TableNo { get; set; }
        public Nullable<System.DateTime> DisDate { get; set; }
        public string Status { get; set; }
    
        public virtual tblFood tblFood { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
